# Generated by Django 4.1.2 on 2023-09-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('features', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Car properties',
                'ordering': ['model', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('additional_contact_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carproperty')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.client')),
            ],
        ),
        migrations.CreateModel(
            name='CarPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('under_repair', 'Under Repair')], default='available', max_length=20)),
                ('daily_rent_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time of update')),
                ('is_published', models.BooleanField(default=True)),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carproperty')),
            ],
            options={
                'verbose_name': 'Post about car',
                'verbose_name_plural': 'Posts about cars',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
